-   id: ember-template-lint
    name: ember-template-lint
    entry: ember-template-lint
    language: node
    types: [file]
    files: "\\.(hbs)$"
    args: []
    require_serial: false
    additional_dependencies: ["ember-template-lint@5.7.3"]
    minimum_pre_commit_version: '0'
